ARG APP_PATH=/opt/outline
#FROM node:22.21.0 AS deps
FROM node:20.19.6 AS deps

ARG APP_PATH
WORKDIR $APP_PATH

RUN corepack enable

COPY ./package.json ./yarn.lock ./.yarnrc.yml ./
COPY ./patches ./patches

RUN corepack prepare yarn@4.11.0 --activate

RUN apt-get update && apt-get install -y cmake
ENV NODE_OPTIONS="--max-old-space-size=24000"

RUN yarn install --refresh-lockfile --network-timeout 1000000 && \
  yarn cache clean

COPY . .
ARG CDN_URL
RUN yarn build

RUN yarn workspaces focus --production && \
  yarn cache clean

ENV PORT=3000
